name: Build containers

on:
  workflow_dispatch:
    inputs:
      target:
        description: Target triple
        required: true

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        id: tag
        run: |
          repo="$(<<< '${{ github.repository }}' tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=name::ghcr.io/$repo:${{ github.event.inputs.target }}"
      - name: Build
        run: |
          docker build \
            --tag='${{ steps.tag.outputs.name }}' \
            --file='docker/Dockerfile.${{ event.inputs.target }}' \
            docker
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: docker push '${{ steps.tag.outputs.name }}'
